package Custom_Exceptions;

import java.util.Scanner;

//Exception class
class MyException extends Exception{
 @Override
 public String toString() {
     return "I am toString()";
 }

 @Override
 public String getMessage() {
     return "I am getMessage()";
 }
}
class MaxAge extends Exception{
 @Override
 public String toString() {
     return "Age cannot be greater than 125";
 }

 @Override
 public String getMessage() {
     return "Make sure that the value of age entered is correct";
 }
}

public class custom_exception_class {
	public static void main(String[] args) {
		 // Exception class example
        int a;
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter a : ");
        a = sc.nextInt();
        if (a<9){
            try {
//                throw new MyException();
                throw new ArithmeticException("this is an exception");
            } catch (Exception e) {
                System.out.println(e.getMessage());
                System.out.println(e.toString());
//                System.out.println(e);
                e.printStackTrace();
                System.out.println("Finished");
            }
            System.out.println("Yes Finished");
        }
	}
}
